### ISSUE TITLE
Tips for table options - date filter

### ISSUE THREAD

**Issue by nygma2004** [PaulWieland/node-red-contrib-saprfc#2]
Hi Paul,

I am finally up and running and I wanted to ask if you have some tips on setting up the filters for table read.
I am trying to filter on a date field in a table and this is what I pass and what I get back from SAP:
![image](https://user-images.githubusercontent.com/16757620/80386322-87f33380-88a7-11ea-9edf-ecc35773c5f8.png)
POSTING_DATE is a DATS 8 field and in SE16 I see the value as DD.MM.YYYY.

**Comment by PaulWieland** [comment]
Typically dates are stored as YYYYMMDD. SE16 is dirty, as it will format values according to your user preferences. Try selecting a single record (ROWCOUNT 1) with NodeRED without a where clause and you will see the true date count.

As far as using `>=`, this works on my system: 

```JavaScript
msg.payload = {
  OPTIONS: [
      "ACCDT >= '20180101' AND ACCDT <= '20181231'",
    ],
}

return msg;
```

**Comment by nygma2004** [comment]
Thanks a lot, works like a charm:
msg.payload = {
  OPTIONS: ["PROCESS_TYPE = 'ZOR'",
            "AND",
            "POSTING_DATE >= '"+date.getFullYear()+""+("0" + (date.getMonth() - 2)).slice(-2)+""+("0" + date.getDate()).slice(-2)+"'"
            ],
    ROWCOUNT: 5000
}
return msg;

I glad you don't mind opening these as issue, whereas these are just general support questions. I am closing this now.

**Comment by PaulWieland** [comment]
Pro tip: if you have to do a lot of date formatting and math, check out [Momentjs](https://momentjs.com) and it's corresponding [NodeRED node](https://github.com/totallyinformation/node-red-contrib-moment).
