### ISSUE TITLE
Nodes don't appear

### ISSUE THREAD

**Issue by ozgursgithub** [PaulWieland/node-red-contrib-saprfc#3]
Hello Paul,
First of all I would like to say thank you for working your saprfc nodes.
Then, I had installed node-red-contrib-saprfc into my system. I could see the saprfc nodes after installing. But after restart they all disappeared. I reinstalled it but nothing changed. 
You can see a screenshot about problem. 
Do you have a reccommendation for this?
![Screenshot_1](https://user-images.githubusercontent.com/41943416/80804130-ee849400-8bbc-11ea-832e-1a43124c0778.png)

Thanks in advance

**Comment by PaulWieland** [comment]
Hi @ozgursgithub do you have any errors in your NodeRED log on the console?

**Comment by PaulWieland** [comment]
Also - search for `call` or `table` instead of `sap`: 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/4663918/80805846-10632400-8b87-11ea-8b16-989ba0b84221.png">

You should see the nodes under a group called sapRFC. For some reason searching for sap doesn't show the group which is a strange behavior of NodeRED itself. 

The items in the redbox that you have in your screenshot are normal. It just shows which nodes are in use - those are not checkboxes.

**Comment by ozgursgithub** [comment]
Hello again Paul,
Thanks for quick response. 
I searched for call and I've collapsed all nodes. But, there is no sapRFC title.
After first installation I had seen it but somehow it disappeared.

![Screenshot_3](https://user-images.githubusercontent.com/41943416/80806486-7e2d4100-8bc3-11ea-8344-afa7ee259ce5.png)

**Comment by PaulWieland** [comment]
and what does your console say when you start NodeRED?

**Comment by ozgursgithub** [comment]
Here;

![image](https://user-images.githubusercontent.com/41943416/80808631-9c497000-8bc8-11ea-9489-358be4350505.png)

**Comment by ozgursgithub** [comment]
When I try to reinstal it, I got these ;
btw, after this I could see sapRFC nodes and then after restart it has disappeared again :/

![image](https://user-images.githubusercontent.com/41943416/80811234-221bea00-8bce-11ea-9c4c-b99391a7b4dd.png)

**Comment by PaulWieland** [comment]
I suspect that the underlying `noderfc` is failing after you restart, however it is very strange that the nodes disappear from the pallet and that you get no warnings in the startup log. 

I seem to remember that `noderfc` requires some environment variables to function correctly. Are these persisting between restarts?

**Comment by ozgursgithub** [comment]
I think its about environment variables. I don't know how to install and configure it but I'll try to find a way.

**Comment by ozgursgithub** [comment]
Hello Again Paul,
I've solved problem with correct environment variables settings. 
Thank you for your answers. 
Have a healty days!
